#!/usr/bin/env bash
#
# Blogático: gerador de conteúdo estático
#
#    Copyright (C) 2023  Thiago Lima
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# Parâmetros 
BASEDIR="${pwd}"
DATA="$BASEDIR/data"
OUTPUT="$BASEDIR/output"

echo "Limpando a versão anterior do blog..."
rm -rf $OUTPUT || exit 1

echo "Garantindo a existência das pastas necessárias..."
mkdir -p $OUTPUT || exit 1

echo "Copiando a estrutura de pastas..."
rsync -qav $DATA/ $OUTPUT/ || exit 1

echo "Convertendo todos os arquivos Markdown para HTML..."
find $OUTPUT -name '*mdwn' -exec pandoc -o {}.html {} \; || exit 1

echo "Corrigindo o nome dos arquivos gerados..."
find $OUTPUT -name '*.html' -exec rename 's/\.mdwn.html$/.html/' {} \; || exit 1

echo "Feito! Tenha um bom dia :)"